### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by arunridingsinger** [WebPx/WebPx.AdminLTE.AspNetCore#2]
Error while validating the service descriptor 'ServiceType: WebPx.AdminLTE.IAdminLTE Lifetime: Scoped ImplementationType: WebPx.AdminLTE.AdminLTE': Unable to resolve service for type 'Microsoft.AspNetCore.Http.IHttpContextAccessor' while attempting to activate 'WebPx.AdminLTE.AdminLTE'.

**Comment by jlchavez** [comment]
You need to add support for IHttpContextAccessor by adding a call in the Startup class in the ConfigureServices method:

`services.AddHttpContextAccessor();`

I believe this has to do with .NET Core 3.0+ changes
