### ISSUE TITLE
AdminLTE.AspNetCore WebPx for AspNetCore  MVC

### ISSUE THREAD

**Issue by aboah** [WebPx/WebPx.AdminLTE.AspNetCore#3]
Some of us would be grateful to have this library available for AspNetCore  MVC and not AspNetCore  Razor alone.
Is it possible Sir

**Comment by jlchavez** [comment]
Sorry for the Delay.

Added support for MVC, by moving the template to the Views folder, so that it can be shared by both MVC and Razor Pages. And added a Template site for MVC from where a site can be started.

In a near future update I will add templating support for Visual Studio.

**Comment by jlchavez** [comment]
Added support for View Localations in the Areas in MVC so that any view can be overriden in the Area:

`/Areas/{AreaName}/Views/Shared/{Theme}/{{0}}.cshtml`

or globally for the site in:

`/Views/Shared/{Theme}/{{0}}.cshtml`

this resolves working in MVC and Razor Pages.
